export const homeJson = [
  {
    id: 1,
    img: require('../assets/Images/Shoes/shoe_01.png'),
    bestSeller: 'Best Seller',
    name: 'Nike Jordan',
    price: '$493.00',
    ES: 'XL',
    sizes: [
      {size: '38'},
      {size: '39'},
      {size: '40'},
      {size: '41'},
      {size: '42'},
      {size: '43'},
    ],
    disc: 'Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....',
    shoeColors: [
      {c1: require('../assets/Images/Shoes/shoe_01.png')},
      {c1: require('../assets/Images/Shoes/shoe_02.png')},
      {c1: require('../assets/Images/Shoes/shoe_03.png')},
    ],
  },
  {
    id: 2,
    img: require('../assets/Images/Shoes/shoe_02.png'),
    bestSeller: 'Best Seller',
    name: 'Nike Air Max',
    sizes: [
      {size: '38'},
      {size: '39'},
      {size: '40'},
      {size: '41'},
      {size: '42'},
      {size: '43'},
    ],
    price: '$897.99',
    ES: 'XL',
    disc: 'Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....',
    shoeColors: [
      {c1: require('../assets/Images/Shoes/shoe_04.png')},
      {c1: require('../assets/Images/Shoes/shoe_05.png')},
      {c1: require('../assets/Images/Shoes/shoe_06.png')},
    ],
  },
  {
    id: 3,
    img: require('../assets/Images/Shoes/shoe_03.png'),
    bestSeller: 'Best Seller',
    name: 'Nike Air Max',
    price: '$897.99',
    ES: 'XL',
    sizes: [
      {size: '38'},
      {size: '39'},
      {size: '40'},
      {size: '41'},
      {size: '42'},
      {size: '43'},
    ],
    disc: 'Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....',
    shoeColors: [
      {c1: require('../assets/Images/Shoes/shoe_07.png')},
      {c1: require('../assets/Images/Shoes/shoe_08.png')},
      {c1: require('../assets/Images/Shoes/shoe_09.png')},
    ],
  },
  {
    id: 4,
    img: require('../assets/Images/Shoes/shoe_04.png'),
    bestSeller: 'Best Seller',
    name: 'Nike Air Max',
    price: '$897.99',
    ES: 'L',
    sizes: [
      {size: '38'},
      {size: '39'},
      {size: '40'},
      {size: '41'},
      {size: '42'},
      {size: '43'},
    ],
    disc: 'Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....',
    shoeColors: [
      {c1: require('../assets/Images/Shoes/shoe_10.png')},
      {c1: require('../assets/Images/Shoes/shoe_11.png')},
      {c1: require('../assets/Images/Shoes/shoe_12.png')},
    ],
  },
  {
    id: 5,
    img: require('../assets/Images/Shoes/shoe_05.png'),
    bestSeller: 'Best Seller',
    name: 'Nike Air Max',
    price: '$897.99',
    ES: 'XL',
    sizes: [
      {size: '38'},
      {size: '39'},
      {size: '40'},
      {size: '41'},
      {size: '42'},
      {size: '43'},
    ],
    disc: 'Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....',
    shoeColors: [
      {c1: require('../assets/Images/Shoes/shoe_10.png')},
      {c1: require('../assets/Images/Shoes/shoe_11.png')},
      {c1: require('../assets/Images/Shoes/shoe_12.png')},
    ],
  },
  {
    id: 6,
    img: require('../assets/Images/Shoes/shoe_06.png'),
    bestSeller: 'Best Seller',
    name: 'Nike Air Max',
    price: '$897.99',
    ES: 'XL',
    sizes: [
      {size: '38'},
      {size: '39'},
      {size: '40'},
      {size: '41'},
      {size: '42'},
      {size: '43'},
    ],
    disc: 'Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....',
    shoeColors: [
      {c1: require('../assets/Images/Shoes/shoe_10.png')},
      {c1: require('../assets/Images/Shoes/shoe_11.png')},
      {c1: require('../assets/Images/Shoes/shoe_12.png')},
    ],
  },
  {
    id: 7,
    img: require('../assets/Images/Shoes/shoe_07.png'),
    bestSeller: 'Best Seller',
    name: 'Nike Air Max',
    price: '$897.99',
    ES: 'XL',
    sizes: [
      {size: '38'},
      {size: '39'},
      {size: '40'},
      {size: '41'},
      {size: '42'},
      {size: '43'},
    ],
    disc: 'Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....',
    shoeColors: [
      {c1: require('../assets/Images/Shoes/shoe_10.png')},
      {c1: require('../assets/Images/Shoes/shoe_11.png')},
      {c1: require('../assets/Images/Shoes/shoe_12.png')},
    ],
  },
  {
    id: 8,
    img: require('../assets/Images/Shoes/shoe_08.png'),
    bestSeller: 'Best Seller',
    name: 'Nike Air Max',
    price: '$897.99',
    ES: 'XL',
    sizes: [
      {size: '38'},
      {size: '39'},
      {size: '40'},
      {size: '41'},
      {size: '42'},
      {size: '43'},
    ],
    disc: 'Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....',
    shoeColors: [
      {c1: require('../assets/Images/Shoes/shoe_10.png')},
      {c1: require('../assets/Images/Shoes/shoe_11.png')},
      {c1: require('../assets/Images/Shoes/shoe_12.png')},
    ],
  },
  {
    id: 9,
    img: require('../assets/Images/Shoes/shoe_09.png'),
    bestSeller: 'Best Seller',
    name: 'Nike Air Max',
    price: '$897.99',
    ES: 'XL',
    sizes: [
      {size: '38'},
      {size: '39'},
      {size: '40'},
      {size: '41'},
      {size: '42'},
      {size: '43'},
    ],
    disc: 'Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....',
    shoeColors: [
      {c1: require('../assets/Images/Shoes/shoe_10.png')},
      {c1: require('../assets/Images/Shoes/shoe_11.png')},
      {c1: require('../assets/Images/Shoes/shoe_12.png')},
    ],
  },
  {
    id: 10,
    img: require('../assets/Images/Shoes/shoe_10.png'),
    bestSeller: 'Best Seller',
    name: 'Nike Air Max',
    price: '$897.99',
    ES: 'XL',
    sizes: [
      {size: '38'},
      {size: '39'},
      {size: '40'},
      {size: '41'},
      {size: '42'},
      {size: '43'},
    ],
    disc: 'Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....',
    shoeColors: [
      {c1: require('../assets/Images/Shoes/shoe_10.png')},
      {c1: require('../assets/Images/Shoes/shoe_11.png')},
      {c1: require('../assets/Images/Shoes/shoe_12.png')},
    ],
  },
  {
    id: 11,
    img: require('../assets/Images/Shoes/shoe_11.png'),
    bestSeller: 'Best Seller',
    name: 'Nike Air Max',
    price: '$897.99',
    ES: 'XL',
    sizes: [
      {size: '38'},
      {size: '39'},
      {size: '40'},
      {size: '41'},
      {size: '42'},
      {size: '43'},
    ],
    disc: 'Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....',
    shoeColors: [
      {c1: require('../assets/Images/Shoes/shoe_10.png')},
      {c1: require('../assets/Images/Shoes/shoe_11.png')},
      {c1: require('../assets/Images/Shoes/shoe_12.png')},
    ],
  },
  {
    id: 12,
    img: require('../assets/Images/Shoes/shoe_12.png'),
    bestSeller: 'Best Seller',
    name: 'Nike Air Max',
    price: '$897.99',
    ES: 'XL',
    sizes: [
      {size: '38'},
      {size: '39'},
      {size: '40'},
      {size: '41'},
      {size: '42'},
      {size: '43'},
    ],
    disc: 'Air Jordan is an American brand of basketball shoes athletic, casual, and style clothing produced by Nike....',
    shoeColors: [
      {c1: require('../assets/Images/Shoes/shoe_10.png')},
      {c1: require('../assets/Images/Shoes/shoe_11.png')},
      {c1: require('../assets/Images/Shoes/shoe_12.png')},
    ],
  },
];
